### ISSUE TITLE
cgps delete old rules & lists issue

### ISSUE THREAD

**Issue by dspdhckr1** [mrrfv/cloudflare-gateway-pihole-scripts#137]
`Run npm run cloudflare-delete

> cloudflare-delete
> npm run cloudflare-delete:rule && npm run cloudflare-delete:list

> cloudflare-delete:rule
> node cf_gateway_rule_delete.js

An error occured while making a web request: "Error: Response not OK", retrying. Attempt 1 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 2 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 3 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 4 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 5 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 6 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 7 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 8 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 9 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 10 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 11 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 12 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 13 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 14 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 15 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 16 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 42 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 43 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 44 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 45 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 46 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 47 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 48 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 49 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
An error occured while making a web request: "Error: Response not OK", retrying. Attempt 50 of 50.
THIS IS NORMAL IN MOST CIRCUMSTANCES. Refrain from reporting this as a bug unless the script doesn't automatically recover after several attempts.
file:///home/runner/work/CF1/CF1/lib/helpers.js:131
        throw new Error(`HTTP error! Status: ${response.status} - ${ (data && 'errors' in data) ? data.errors[0].message : data } - ${error}`);
              ^

Error: HTTP error! Status: 404 - Could not route to /client/v4/accounts/***/gateway/rules, perhaps your object identifier is invalid? - Error: Response not OK
    at request (file:///home/runner/work/CF1/CF1/lib/helpers.js:131:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///home/runner/work/CF1/CF1/cf_gateway_rule_delete.js:4:27

Node.js v22.11.0
Error: Process completed with exit code 1.`

**Comment by mrrfv** [comment]
Make sure your `CLOUDFLARE_ACCOUNT_ID` is set correctly. See here for details: https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/blob/main/extended_guide.md#cloudflare_account_id
