### ISSUE TITLE
cgps Process completed with exit code 1.

### ISSUE THREAD

**Issue by suricloud** [mrrfv/cloudflare-gateway-pihole-scripts#33]
Hi,

I have the latest version forked, and synced yesterday the new update.
Now when i want to update my filter list, i get this error.

at new URL (node:internal/url:637:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at fetch2 (node:internal/deps/undici/undici:10715:25)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:[24](https://github.com/suricloud/cloudflare-gateway-pihole-scripts/actions/runs/6324602898/job/17174424493#step:6:25)2:[25](https://github.com/suricloud/cloudflare-gateway-pihole-scripts/actions/runs/6324602898/job/17174424493#step:6:26))
      at file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/utils.js:60:57
      at Array.map (<anonymous>)
      at downloadFiles (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/utils.js:60:44)
      at downloadLists (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/download_lists.js:18:9) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.18.0
Error: Process completed with exit code 1.

**Comment by willbelove1** [comment]
Please fix this error, I also get into this trouble :( !!!

**Comment by mrrfv** [comment]
I've just pushed a possible fix for this issue, try again. If that's not going to work, please provide detailed information about your setup so I can understand the problem better, such as:

- the environment you're running the scripts in (e.g. is it macOS? GitHub Actions? Raspberry Pi?)
- are you using custom blocklist and allowlist URLs? which ones?

**Comment by suricloud** [comment]
Hi,

Running on github forked.
using block and allow list in " variables"
hagezi wild card pro blocklist 
hagezi referral white list

**Comment by willbelove1** [comment]
Run node cf_gateway_rule_delete.js
  node cf_gateway_rule_delete.js
  node cf_list_delete.js
  shell: /usr/bin/bash -e {0}
  env:
    NODE_ENV: production
    CLOUDFLARE_API_KEY: 
    CLOUDFLARE_ACCOUNT_EMAIL: 
    CLOUDFLARE_ACCOUNT_ID: 
    CLOUDFLARE_LIST_ITEM_LIMIT: 
    FAST_MODE: 1
file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:34
    throw new Error(`HTTP error! Status: ${response.status}`);
          ^

Error: HTTP error! Status: 404
    at request (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:34:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/cf_gateway_rule_delete.js:3:[2](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:2)[7](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:7)

Node.js v1[8](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:8).[17](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:18).1
Error: Process completed with exit code 1.


=>>> Now I got into this trouble ? Can you show me how to fix it please ? Thanks in advance !

**Comment by hlqviet** [comment]
> Run node cf_gateway_rule_delete.js node cf_gateway_rule_delete.js node cf_list_delete.js shell: /usr/bin/bash -e {0} env: NODE_ENV: production CLOUDFLARE_API_KEY: CLOUDFLARE_ACCOUNT_EMAIL: CLOUDFLARE_ACCOUNT_ID: CLOUDFLARE_LIST_ITEM_LIMIT: FAST_MODE: 1 file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:34 throw new Error(`HTTP error! Status: ${response.status}`); ^
> 
> Error: HTTP error! Status: 404 at request (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:34:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/cf_gateway_rule_delete.js:3:[2](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:2)[7](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:7)
> 
> Node.js v1[8](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:8).[17](https://github.com/willbelove1/cloudflare-gateway-pihole-scripts/actions/runs/6333543169/job/17201816849#step:7:18).1 Error: Process completed with exit code 1.
> 
> =>>> Now I got into this trouble ? Can you show me how to fix it please ? Thanks in advance !

You haven't added your secrets
```
CLOUDFLARE_API_KEY:
CLOUDFLARE_ACCOUNT_EMAIL:
CLOUDFLARE_ACCOUNT_ID:
CLOUDFLARE_LIST_ITEM_LIMIT:
```

**Comment by willbelove1** [comment]
No, you are wrong HLQVIET. I put everthing in serects. But it never runs ?

**Comment by mrrfv** [comment]
It does indeed look like you haven't added the secrets properly. Could you please make sure that you added them in `Repository Settings` -> `Secrets and variables` -> `Actions` and not anywhere else? Are they the correct name?

**Comment by suricloud** [comment]
For me all working fine now,after these updates.Thanks for the quick fix.
