### ISSUE TITLE
Error: HTTP error! Status: 502

### ISSUE THREAD

**Issue by suricloud** [mrrfv/cloudflare-gateway-pihole-scripts#53]
Hi,

I just synced with the latest,and now getting these errors.

Could not create "CGPS List - Chunk 140" - Error: HTTP error! Status: 502
file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:106
    throw new Error(`HTTP error! Status: ${response.status}`);
          ^

Error: HTTP error! Status: 502
    at request (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:106:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createZeroTrustListsOneByOne (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/api.js:48:7)
    at async file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/cf_list_create.js:140:5

Node.js v20.9.0
Error: Process completed with exit code 1.

**Comment by mrrfv** [comment]
For future reference: 502 is a server-side error, meaning it happened on Cloudflare's side and CGPS can do nothing about it. Fast mode might occasionally cause such errors when the servers can't keep up.
