### ISSUE TITLE
Create or delete lists script error

### ISSUE THREAD

**Issue by mcteixeira** [mrrfv/cloudflare-gateway-pihole-scripts#61]
Hello,

I I run create lists script (and also delete lists script) I run into this error:

```
Creating 169 lists for 168793 domains...
Could not create "CGPS List - Chunk 1" - Error: HTTP error! Status: 400
file:///srv/cloudflare-gateway-pihole-scripts/lib/helpers.js:106
    throw new Error(`HTTP error! Status: ${response.status}`);
          ^

Error: HTTP error! Status: 400
    at request (file:///srv/cloudflare-gateway-pihole-scripts/lib/helpers.js:106:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createZeroTrustListsOneByOne (file:///srv/cloudflare-gateway-pihole-scripts/lib/api.js:48:7)
    at async file:///srv/cloudflare-gateway-pihole-scripts/cf_list_create.js:140:5

```

The error is the same as above for the delete lists script.

**Comment by mcteixeira** [comment]
Hello,

I'm sorry. I was using API Global Key. Using a newly created API token worked :)

**Comment by mrrfv** [comment]
Happy to hear! I just updated the README to make it clear that a token has to be used.
